### ISSUE TITLE
Icons Ribbon Area - Assign same icon multiple times.

### ISSUE THREAD

**Issue by sazizrahman** [umaranis/MindMate#10]
Clicking on the same icon multiple times will assign the same icon multiple times to the node. Check the attachment.

![u-multi icon issue](https://cloud.githubusercontent.com/assets/20092505/16270784/271f2b66-385d-11e6-98dc-128ea742b563.PNG)

**Comment by umaranis** [comment]
This is generally allowed in Mind Maps. Consider this use case.

![image](https://cloud.githubusercontent.com/assets/2135071/16330596/78ba1810-39fb-11e6-837c-135481962fcb.png)
