### ISSUE TITLE
Installer - Unrecognized App

### ISSUE THREAD

**Issue by sazizrahman** [umaranis/MindMate#11]
Is there any way to improve it?

![umar1](https://cloud.githubusercontent.com/assets/20092505/16270916/99477be4-385d-11e6-99e0-e89674780a30.PNG)

**Comment by padillah** [comment]
This has nothing to do with the software, it is a default response that Windows has to files copied over the internet. If you right-click on the file and go to Properties you will see a checkbox for "Unblock". Mark this checkbox and click Ok, then try to install again.

**Comment by umaranis** [comment]
Thanks, @padillah 
Closing this issue.
