### ISSUE TITLE
Open the saved *.mm file with Notepad++ and get messy code

### ISSUE THREAD

**Issue by valuex** [umaranis/MindMate#63]
OS: Win10
MindMate version: v0.6 beta, portable
I am trying to understand how MindMate saves data.
When I save the file and open it with notepadd++, I get some un-readable codes as below.
Can you share your comment on how to fix this? Thanks.
And from the mm file, I found that, there is no id  , no hirachichy info , and  no exact coordinate for each node, can you share that how MindMate distinguish each node and find its paresent node and sibling node and then draw it at the desired postion on the convase ? 
Thanks again for shareing this wonderful work.  
`PK    Q?g$?  ?     MindMate.xml?~?map version="0.9.0"><attribute_registry><attribute_name NAME="Completion Date" VISIBLE="True" RESTRICTED="False" TYPE="System" DATATYPE="DateTime" LISTOPTION="NoList" /><attribute_name NAME="Task Status" VISIBLE="True" RESTRICTED="False" TYPE="System" DATATYPE="DateTime" LISTOPTION="NoList" /></attribute_registry><node TEXT="Test" CREATED="1607803129577" MODIFIED="1607803618888"><node POSITION="right" TEXT="subl1c1" CREATED="1607803137600" MODIFIED="1607803153437"><node TEXT="subl2c1" CREATED="1607803148834" MODIFIED="1607803153032" /><node TEXT="subl2c2" CREATED="1607803153437" MODIFIED="1607803158273" /></node><node POSITION="left" TEXT="subl1c2" CREATED="1607803618888" MODIFIED="1607803726325" LINK="https://cn.bing.com/"><icon BUILTIN="ksmiletris" /><attribute NAME="Completion Date" VALUE="12/12/2020 20:08:06" /><attribute NAME="Task Status" VALUE="Complete" /></node></node></map>PK     Q?g$?  ?                   MindMate.xmlPK      :   ?    `

**Comment by umaranis** [comment]
Hi @valuex ,

It is basically a zip file.. change the extension to .zip and you should be able to see the contents.

The .mm zip file contains an XML file and the images added to the map and notes. The structure of the map (i.e. the relationship between nodes) and text are stored in the XML file.

**Comment by valuex** [comment]
Hi @umaranis , Note with thanks.  I think the *.mm file used here is not the same as the one used by FreeMind, which is not zipped. :-)
