### ISSUE TITLE
Ability to set font/format (bold/italic) on map level

### ISSUE THREAD

**Issue by sazizrahman** [umaranis/MindMate#66]

**Comment by sazizrahman** [comment]
It will be nice to have a way set the default formatting options for the whole map. 
User should still be able to override it on a node level.

**Comment by umaranis** [comment]
commit ref: a21aedbc0c1b463ddb8b5537a3523beb638ffb78 and e1aaa9f3c3b3fef95cbfee1c6b116b7601fe825d
