### ISSUE TITLE
[upgrade] Can we have a new portable build other than v0.7? can we support Win10/11 project file for Visual 2019 ?

### ISSUE THREAD

**Issue by nykevinwong** [umaranis/MindMate#78]
Hi Umaranis,
I am currently using MindMate v0.7, but version 0.7 does not support Unicode file for reading/writing Chinese/non-English language, which is fixed by you around 2022.

I tried to create a latest build via Visual Studio 2019 on Windows 11, but unfortunately I am getting below error after nuget restore process.
I don't have Windows 7 SDK for UICC.exe and Visual 2017. how can I make it compatible with VS2019 & Windows 11?
can you release a new portable build based on the latest code ?

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Program Files (x86)\Windows Kits\10\bin\x86\UICC.exe" "C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.xml" "C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.bml" /res:"C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.rc" 

"C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe" /v "C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.rc" 

cmd /c "("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat") && ("link.exe" /VERBOSE /NOENTRY /DLL /OUT:"C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.ribbon" "C:\DEV\production\MindMate\MindMate.Win7\View\Ribbon\RibbonMarkup.res")"" exited with code 1.	MindMate.Win7			

Thanks,
Kevin

**Comment by nykevinwong** [comment]
I think I can solve this issue.  
UICC.exe and rc.exe requires VC++ installation, and switching to VS 2019 requires the change pathname.

**Comment by umaranis** [comment]
@nykevinwong happy that you were able to build it yourself.

I will upload a new release soon with the fix.

Thanks.
