### ISSUE TITLE
Icons Ribbon Area- Show selected when node clicked.

### ISSUE THREAD

**Issue by sazizrahman** [umaranis/MindMate#9]
As compare to MS word's heading area, the corresponding icons should be selected automatically as soon as the node is clicked.
Example: If there is a node with Task and Source icon and it is clicked, both of these icons should become selected in the Icons ribbon area.

**Comment by umaranis** [comment]
One icon can be selected many times. 

If selected icon shows as selected, it will give an impression that clicking it will deselect it. Which is not the case because one icon can be selected many times.
