### ISSUE TITLE
Solution of Chinese Messy Code ?

### ISSUE THREAD

**Issue by huster-songtao** [umaranis/MindMate#90]
![20230907144740](https://github.com/umaranis/MindMate/assets/94954133/2bbc53e4-3047-4e22-8084-a0a03d4a3bf4)

**Comment by umaranis** [comment]
Hi @huster-songtao ,

it is resolved in the master branch but the latest release doesn't have that fix. I will publish a new release soon with the fix included.

**Comment by umaranis** [comment]
Hi @huster-songtao ,

I have created a new release (v0.8) that includes the fix for this issue.

Could you give it a try? Thanks
